Repository bloom-works/ownpath, pull requests merged in 2022-08, with the labels that each got.

#20 Link styles
  src/components/Footer.tsx
  src/index.css
Labels: release-patch

#17 Add back button to guided search
  src/components/BackButton.tsx
  src/index.css
  src/pages/GuidedSearch.tsx
  src/pages/ResultDetail.tsx
  src/translations/en/pages.json
  src/translations/es/pages.json
Labels: release-patch

#26 Incorporate LADDERS push 20220803-221849656
  raw_data/ladders.csv
Labels: release-patch

#16 Adds spanish language mi propia senda logo
  src/components/Layout.tsx
  src/images/logos/mi_propia_senda.svg
  src/index.css
  src/translations/en/components.json
  src/translations/es/components.json
Labels: release-patch

#22 Jest-Axe(a11y) Tests
  package-lock.json
  package.json
  src/App.tsx
  src/a11y.test.tsx
  src/components/Home/ContentCard.tsx
  src/components/Home/GuidedSearchCard.tsx
  src/components/Layout.tsx
  src/components/Search/Filters/TypeOfHelpInput.tsx
  src/components/ShareButton.tsx
  src/index.css
  src/pages/GuidedSearch.tsx
  src/pages/Home.tsx
  src/setupTests.ts
  src/testHelper.tsx
  src/utils.test.tsx
  tsconfig.json
Labels: enhancement, release-minor

#28 Incorporate LADDERS push 20220804-213426454
  raw_data/ladders.csv
Labels: release-patch

#25 Adds button to increase distance when no results
  src/components/Search/Filters/Control/DesktopControl.tsx
  src/components/Search/Filters/Control/MobileControl.tsx
  src/pages/Search/Search.tsx
  src/translations/en/pages.json
  src/translations/es/pages.json
Labels: release-minor

#30 Incorporate LADDERS push 20220808-201020967
  raw_data/ladders.csv
Labels: release-patch

#33 Incorporate LADDERS push 20220809-192838207
  raw_data/ladders.csv
Labels: release-patch

#32 Browser Back Button
  src/pages/Home.tsx
  src/pages/Search/DesktopResults.tsx
Labels: bug, release-minor

#36 Incorporate LADDERS push 20220812-172933666
  raw_data/ladders.csv
Labels: release-patch

#35 Normalized Hero Banner and Content
  src/pages/Home.tsx
Labels: bug, release-minor

#34 Translations overhaul
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/components/Banner.tsx
  src/components/BulletedList.tsx
  src/components/Footer.tsx
  src/components/GuidedSearch/HelpRecipientInput.tsx
  src/components/Home/ContentCard.tsx
  src/components/Home/GuidedSearchCard.tsx
  src/components/Home/ZipCard.tsx
  src/components/Layout.tsx
  src/components/Map.tsx
  src/components/ResultDetail/BasicResultDetail.tsx
  src/components/ResultDetail/DirectionsLink.tsx
  src/components/ResultDetail/Hours.tsx
  src/components/Search/Filters/AccessibilityInput.tsx
  src/components/Search/Filters/AgeGroupInput.tsx
  src/components/Search/Filters/Control/DesktopControl.tsx
  src/components/Search/Filters/Control/DesktopControlDropdown.tsx
  src/components/Search/Filters/Control/DesktopControlToggles.tsx
  src/components/Search/Filters/Control/MobileControl.tsx
  src/components/Search/Filters/DistanceInput.tsx
  src/components/Search/Filters/FeePreferenceInput.tsx
  src/components/Search/Filters/FilterCheckbox.tsx
  src/components/Search/Filters/FilterRadio.tsx
  src/components/Search/Filters/HoursInput.tsx
  src/components/Search/Filters/LanguageInput.tsx
  src/components/Search/Filters/TypeOfHelpInput.tsx
  src/components/Search/MilesAway.tsx
  src/components/Search/MobileViewToggle.tsx
  src/components/Search/ResultCard.tsx
  src/components/ZipInput.tsx
  src/i18n.ts
  src/pages/GuidedSearch.tsx
  src/pages/Home.tsx
  src/pages/NotFound.tsx
  src/pages/ResultDetail.tsx
  src/pages/Search/DesktopResults.tsx
  src/pages/Search/MobileResults.tsx
  src/pages/Search/Search.tsx
  src/translations/en/common.json
  src/translations/en/components.json
  src/translations/en/pages.json
  src/translations/en_translations.json
  src/translations/es/common.json
  src/translations/es/components.json
  src/translations/es/pages.json
  src/translations/es_translations.json
  src/translations/generate_translations.ts
  src/utils/search.ts
Labels: release-patch

#29 Streamline zipcode edit UI in search results
  src/components/ZipInput.tsx
  src/index.css
  src/pages/Search/Search.tsx
Labels: enhancement, release-minor

#38 fix browser back behavior
  src/pages/Search/DesktopResults.tsx
Labels: release-patch

#19 <ShareButton /> mobile fixes
  package-lock.json
  package.json
  src/components/ShareButton.tsx
  src/index.css
  src/pages/ResultDetail.tsx
  src/pages/Search/Search.tsx
Labels: bug, release-patch

#39 exclude dev & staging traffic in google analytics
  public/index.html
Labels: release-patch

#42 Un-quote link for colorado crisis services
  src/translations/en_translations.json
  src/translations/es_translations.json
  src/translations/generate_translations.ts
Labels: release-patch

#45 swap to use CO analytics account
  public/index.html
  src/analytics.ts
Labels: release-patch

#43 numbered search results + map markers
  src/components/Map.tsx
  src/components/Search/ResultCard.tsx
  src/components/Search/ResultsList.tsx
  src/images/map-marker-active.svg
  src/images/map-marker.svg
  src/index.css
  src/pages/ResultDetail.tsx
  src/pages/Search/DesktopResults.tsx
  src/pages/Search/MobileResults.tsx
  src/types/search.ts
  src/utils.test.tsx
  src/utils/filters/accessibility.ts
  src/utils/filters/age.ts
  src/utils/filters/distance.ts
  src/utils/filters/feePreference.ts
  src/utils/filters/hours.ts
  src/utils/filters/languages.ts
  src/utils/filters/typeOfHelp.ts
  src/utils/index.ts
  src/utils/map.ts
  src/utils/search.ts
Labels: release-patch

#41 bugfix: don't show empty lists of services
  src/pages/ResultDetail.tsx
Labels: release-patch

#48 Add dev to reviewers for ladders data updates
  .github/CODEOWNERS
Labels: release-patch

#44 Incorporate LADDERS push 20220818-190255490
  raw_data/ladders.csv
Labels: release-patch

#52 Incorporate LADDERS push 20220822-173708758
  raw_data/ladders.csv
Labels: release-patch

#47 Faq
  package-lock.json
  package.json
  public/resources/BHA OwnPath FAQs (EN).pdf
  public/resources/BHA OwnPath FAQs (ES).pdf
  public/resources/BHA OwnPath one pager (EN).pdf
  public/resources/BHA OwnPath one pager (ES).pdf
  src/App.tsx
  src/a11y.test.tsx
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/index.css
  src/pages/FAQ.tsx
  src/translations/en_translations.json
  src/translations/es_translations.json
  src/translations/generate_translations.ts
Labels: release-minor

#58 Incorporate LADDERS push 20220824-142530172
  raw_data/ladders.csv
Labels: release-patch

#56 fix nav styling on mobile
  src/components/Layout.tsx
Labels: release-patch

#53 Adds title attribute to ownpath logo
  src/components/Layout.tsx
Labels: release-patch

#54 add provider last updated date
  src/data/process_data.ts
  src/pages/ResultDetail.tsx
  src/translations/en_translations.json
  src/translations/es_translations.json
  src/types/care_provider.ts
  src/utils.test.tsx
Labels: release-patch

#57 app alert cleanup + mobile fixes
  src/components/AppAlert.tsx
  src/components/Layout.tsx
  src/components/Search/Filters/TypeOfHelpInput.tsx
  src/pages/GuidedSearch.tsx
Labels: release-patch

#63 Incorporate LADDERS push 20220829-140500796
  raw_data/ladders.csv
Labels: release-patch

#64 debug mode fix
  public/index.html
Labels: release-patch

#61 playwright config
  .github/workflows/browser_tests.yml
  .github/workflows/pull_request.yml
Labels: release-patch

#66 Incorporate LADDERS push 20220830-142844709
  raw_data/ladders.csv
Labels: release-patch

#65 mobile styling polish
  e2e/guided-search.spec.ts
  src/components/Banner.tsx
  src/components/Footer.tsx
  src/components/Home/GuidedSearchCard.tsx
  src/components/Home/ZipCard.tsx
  src/components/Layout.tsx
  src/components/ZipInput.tsx
  src/index.css
  src/pages/Home.tsx
Labels: release-patch

#69 Incorporate LADDERS push 20220831-132614072
  raw_data/ladders.csv
Labels: release-patch
