Repository bloom-works/ownpath, pull requests merged in 2022-11, with the labels that each got.

#133 Adds compare selection UI component
  src/components/Compare/CompareDetail.tsx
  src/components/Compare/CompareSelector.tsx
  src/components/Compare/Selections.tsx
  src/images/caret-down.svg
  src/index.css
  src/pages/Compare.tsx
  src/translations/en_translations.json
  src/translations/es_translations.json
Labels: release-minor

#142 Incorporate LADDERS push 20221101-141634740
  raw_data/ladders.csv
Labels: release-patch

#137 Accessibility fixes provider names links
  src/components/Search/ResultCard.tsx
Labels: release-patch

#143 Incorporate LADDERS push 20221102-140748636
  raw_data/ladders.csv
Labels: release-patch

#141 make compare page zip-aware
  src/components/Compare/CompareDetail.tsx
  src/components/Search/MilesAway.tsx
  src/pages/Compare.tsx
  src/translations/en_translations.json
  src/utils/filters/distance.ts
  src/utils/search.ts
Labels: release-patch

#136 Accesibility fixes focus
  src/a11y.test.tsx
  src/components/Home/ZipCard.tsx
  src/components/Search/Filters/AccessibilityInput.tsx
  src/components/Search/Filters/AgeGroupInput.tsx
  src/components/Search/Filters/Control/DesktopControlToggles.tsx
  src/components/Search/Filters/Control/MobileControl.tsx
  src/components/Search/Filters/DistanceInput.tsx
  src/components/Search/Filters/FeePreferenceInput.tsx
  src/components/Search/Filters/HoursInput.tsx
  src/components/Search/Filters/LanguageInput.tsx
  src/components/Search/Filters/TypeOfHelpInput.tsx
  src/components/ShareButton.tsx
  src/pages/Compare.tsx
  src/pages/FAQ.tsx
  src/pages/GuidedSearch.tsx
  src/pages/Home.tsx
  src/pages/NotFound.tsx
  src/pages/ResultDetail.tsx
  src/pages/Search/DesktopResults.tsx
  src/pages/Search/MobileResults.tsx
  src/pages/Search/Search.tsx
  src/utils/accessibility.ts
  src/utils/analytics.ts
  src/utils/index.ts
Labels: release-patch

#144 hours of operation table
  src/components/Compare/CompareStripedRows.tsx
  src/components/Compare/HoursTable.tsx
  src/pages/Compare.tsx
Labels: release-patch

#146 Incorporate LADDERS push 20221104-141802216
  raw_data/ladders.csv
Labels: release-patch

#148 Incorporate LADDERS push 20221107-150730741
  raw_data/ladders.csv
Labels: release-patch

#147 add payment types table to compare page
  src/components/Compare/CompareStripedRows.tsx
  src/components/Compare/FeesTable.tsx
  src/components/Compare/HoursTable.tsx
  src/images/check.svg
  src/pages/Compare.tsx
Labels: release-patch

#157 Incorporate LADDERS push 20221109-152738795
  raw_data/ladders.csv
Labels: release-patch

#155 Add Git pre commit hook
  .husky/pre-commit
  package-lock.json
  package.json
  src/a11y.test.tsx
  src/components/HighlightBox.tsx
  src/components/Map.tsx
  src/components/Search/Filters/Control/DesktopControl.tsx
  src/data/zip_report.ts
  src/pages/Compare.tsx
  src/pages/Search/Search.tsx
  src/translations/generate_translations.ts
  src/utils/search.ts
Labels: release-patch

#153 more compare tables
  src/components/Compare/CompareStripedRows.tsx
  src/components/Compare/FeesTable.tsx
  src/components/Compare/HoursTable.tsx
  src/components/Compare/LanguagesTable.tsx
  src/components/Compare/PopulationsTable.tsx
  src/pages/Compare.tsx
Labels: release-patch

#154 compare alignment, refactor
  src/components/Compare/CompareDetail.tsx
  src/pages/Compare.tsx
  src/utils/search.ts
Labels: release-patch

#159 Incorporate LADDERS push 20221110-153940456
  raw_data/ladders.csv
Labels: release-patch

#149 Accessibility more fixes
  e2e/search.spec.ts
  src/components/Search/Filters/Control/DesktopControl.tsx
  src/components/Search/Filters/Control/DesktopControlToggles.tsx
  src/components/Search/ResultCard.tsx
  src/translations/es_translations.json
Labels: release-patch

#158 add remaining content to compare page
  src/components/Compare/AccessibilityTable.tsx
  src/components/Compare/MentalHealthServicesTable.tsx
  src/components/Compare/SubstanceUseServicesTable.tsx
  src/pages/Compare.tsx
  src/translations/en_translations.json
  src/translations/es_translations.json
Labels: release-patch

#163 Accessibility titles
  src/a11y.test.tsx
  src/components/Layout.tsx
  src/pages/Compare.tsx
  src/pages/FAQ.tsx
  src/pages/GuidedSearch.tsx
  src/pages/Home.tsx
  src/pages/NotFound.tsx
  src/pages/ResultDetail.tsx
  src/pages/Search/Search.tsx
  src/translations/en_translations.json
  src/translations/es_translations.json
  src/utils/accessibility.ts
Labels: release-patch

#162 Incorporate LADDERS push 20221114-150806352
  raw_data/ladders.csv
Labels: release-patch

#168 Incorporate LADDERS push 20221116-165618706
  raw_data/ladders.csv
Labels: release-minor

#164 Move dependabot.yml into .github directory
  .github/dependabot.yml
Labels: release-minor

#165 Remove map elements from keyboard navigation hierarchy
  src/components/Map.tsx
  src/pages/Compare.tsx
  src/pages/ResultDetail.tsx
  src/pages/Search/DesktopResults.tsx
  src/pages/Search/MobileResults.tsx
Labels: release-patch

#166 Wire in accepting new patients and telehealth badge
  src/components/Badge.tsx
  src/components/ResultDetail/BasicResultDetail.tsx
  src/data/process_data.ts
  src/types/care_provider.ts
  src/utils.test.tsx
Labels: release-patch

#175 Add Peer Support to substance use list
  .gitignore
  README.md
  src/data/process_data.ts
  src/translations/en_translations.json
  src/translations/es_translations.json
  src/types/care_provider.ts
  src/utils.test.tsx
Labels: release-patch

#176 Incorporate LADDERS push 20221118-145437557
  raw_data/ladders.csv
  src/components/Badge.tsx
  src/components/Compare/CompareDetail.tsx
  src/components/ResultDetail/BasicResultDetail.tsx
  src/pages/ResultDetail.tsx
Labels: release-patch

#187 Incorporate LADDERS push 20221123-154448283
  raw_data/ladders.csv
Labels: release-patch

#160 Adds checkboxes to result list; moves compare selector to search
  e2e/compare.spec.ts
  e2e/search.spec.ts
  package-lock.json
  src/a11y.test.tsx
  src/components/Compare/CompareDetail.tsx
  src/components/Compare/CompareSelector.tsx
  src/components/Compare/CompareStripedRows.tsx
  src/components/Compare/HoursTable.tsx
  src/components/Compare/Selections.tsx
  src/components/Search/ResultCard.tsx
  src/components/Search/ResultsList.tsx
  src/components/Search/ResultsMap.tsx
  src/index.css
  src/pages/Compare.tsx
  src/pages/Search/Search.tsx
  src/utils/analytics.ts
Labels: release-major

#191 Incorporate LADDERS push 20221129-145515907
  raw_data/ladders.csv
Labels: release-patch
